name: first workflow
on:
  repository_dispatch: 
    types: [test]
    push:
        branches:
            - "main"
jobs:
    first_workflow_job:
        name: first-jop      
        runs-on: ubuntu-latest
        steps:
            - name: First WF
              run: ls
              shell: bash
              