name: first workflow
on:
  push
#  workflow_dispatch:
#    inputs:
#      versionName:
#        required: true
#        description: "this is version name for github workflow"
#  repository_dispatch: 
#    types: [test]

#  push:
#    branches:
#      - "main"
#  pull_request: 
#    branches:
#      - "feature"
#    types: [opened, closed]

jobs:
  first_workflow_job:
    name: first-job      
    runs-on: ubuntu-latest
    steps:
      - name: Run echo command
        if: github.ref== 'refs/head/feature'
        run: echo "elzoz"
        shell: bash
