name: first workflow
on:
    push:
        branches:
            - "main"
jobs:
    first_workflow_job:
        name: first-jop      
        runs-on: ubuntu-latest
        steps:
            - name: run bash command
              run: echo "elzoz"
              