name: first workflow
on:
    push:
        branches:
            - "main"
jobs:
    first_workflow_job:
        name: first-jop      
        runs-on: ubuntu-latest
        steps:
            - name: before checkout action
              run: ls
              shell: bash

            - name: checkout step
              uses: actions/checkout@v3

            - name: after checkout
              run: ls
              shell: bash
              